### ISSUE TITLE
dict2xml doesn't work on python 3.2

### ISSUE THREAD

**Issue by Gldkslfmsd** [delfick/python-dict2xml#9]
Hello,
it seems that your library isn't compatible with python 3.2. Are you going to fix it?
```
Python 3.2.3 (default, Jun 18 2015, 21:46:58) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dict2xml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/machacek/.virtualenvs/p3.2/lib/python3.2/site-packages/dict2xml-1.4-py3.2.egg/dict2xml/__init__.py", line 1, in <module>
  File "/home/machacek/.virtualenvs/p3.2/lib/python3.2/site-packages/dict2xml-1.4-py3.2.egg/dict2xml/logic.py", line 7
    u"(:|[A-Z]|_|[a-z]|[\xC0-\xD6]|[\xD8-\xF6]|[\xF8-\u02FF]|[\u0370-\u037D]|[\u037F-\u1FFF]|[\u200C-\u200D]|[\u2070-\u218F]|[\u2C00-\u2FEF]|[\u3001-\uD7FF]|[\uF900-\uFDCF]|[\uFDF0-\uFFFD])",
                                                                                                                                                                                             ^
SyntaxError: invalid syntax
>>>  
```

**Comment by delfick** [comment]
sorry, I'm only supporting later versions of python3

    ┌─(stephen.moore@iambob-iLaptop, 04 Dec)(venv)────────────(~/Projects/utility/python-dict2xml)────┐
    └─(16:39)Ɣ python
    Python 3.4.3 (default, Jul 13 2015, 12:18:23)
    [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import dict2xml
    >>>
